// Package contactsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package contactsapi

// Contact defines model for Contact.
type Contact struct {
	FamilyName  string `json:"familyName"`
	FirstName   string `json:"firstName"`
	Id          string `json:"id"`
	PhoneNumber string `json:"phoneNumber"`
}

// ContactList defines model for ContactList.
type ContactList struct {
	Items []Contact `json:"items"`
}

// ContactValues defines model for ContactValues.
type ContactValues struct {
	FamilyName  string `json:"familyName"`
	FirstName   string `json:"firstName"`
	PhoneNumber string `json:"phoneNumber"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetContactListParams defines parameters for GetContactList.
type GetContactListParams struct {
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddContactJSONRequestBody defines body for AddContact for application/json ContentType.
type AddContactJSONRequestBody = ContactValues
